name: Node.js Package Beta

on:
  # Trigger the workflow from any feature branch
  workflow_dispatch:
    inputs:
      betaVersion:
        description: 'Version tag for the beta job'
        required: true
        type: number

jobs:
  publish-npm-beta:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: Set up Git user information
        run: |
          git config --global user.name 'GIT Package Updater'
          git config --global user.email 'julienboz@noreply.github.com'
      - name: Update version to beta
        run: |
          npm version prerelease --preid=beta -m "Upgrade to %s"
          git push
      - run: npm publish --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
